version: "3.9"
services:
  api:
    build: { context: ./backend, dockerfile: ../docker/Dockerfile.api }
    env_file: .env
    ports: ["8000:8000"]
    depends_on:
      - redis
      - qdrant
    volumes:
      - ./backend:/app
      - ./data:/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:v1.11.3
    ports: ["6333:6333"]
    volumes:
      - ./qdrant_data:/qdrant/storage
